print("== mod_init.lua ==")
print("test", lazuli.get_pid)
print("pid is", lazuli.get_pid())
print("uid is", lazuli.get_uid())
print(lazuli.get_param())
print("== event test ==")
lazuli.register_event("key_down")
print("waiting for key_down")
lazuli.block_event()
local event = lazuli.pop_event()
print("got", event[1], event[2], event[3], event[4], event[5], event[6])
lazuli.unregister_event("key_down")
print("== end of init ==")
lazuli.sleep(5)
lazuli.halt()
